### ISSUE TITLE
Crash bug with unreal 4.26.2

### ISSUE THREAD

**Issue by HeadClot** [HoussineMehnik/UE4-MeshSwapperPlugin#3]
I am running into a crash bug with the Static mesh swapper plugin. 

When I click on a directory with an asset that contains a Mesh Swapper asset. It crashes Unreal 4.

I have attached a zip file which contains a minidump file and a my crash log that I got.

[UE4Minidump.zip](https://github.com/mhousse1247/UE4-MeshSwapperPlugin/files/6560625/UE4Minidump.zip)

```
LowLevelFatalError [File:C:\Program Files\Epic Games\UE_4.26\Engine\Source\Editor\UnrealEd\Classes\ThumbnailRendering/ThumbnailRenderer.h] [Line: 70] Pure virtual not implemented (UThumbnailRenderer::Draw)

UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll
```

**Comment by loureed927** [comment]
the cause of this crash is explictly shown in your log. You have to implement new version of pure virtual fucntion Draw for your thnumbnail renderer. the previously worked Draw function has been deprecated since UE4.25
